name: main
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      # https://github.com/actions/virtual-environments/issues/710
      - name: Add emoji font 🤩
        run: sudo apt-get install fonts-noto-color-emoji -y

      - name: Run tests 🧪
        uses: cypress-io/github-action@v2
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
