name: main
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Add Chinese fonts
        run: |
          sudo apt-get update -y
          sudo apt-get install language-pack-zh* -y
          sudo apt-get install chinese* -y

      - name: Run tests 🧪
        uses: cypress-io/github-action@v2
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
